# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- intellij_DevOps

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '${Build.SourcesDirectory}'
    Contents: '**'
    TargetFolder: '${Build.ArtifactStagingDirectory}'

- script: |
    ./gradlew build publishPlugin
  displayName: 'Build and Publish Plugin'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'build/distributions'
    artifactName: 'IntelliJPlugin'   
    publishLocation: 'Container'